[versions]
accompanist = "0.31.1-alpha"
agp = "8.0.0"
androidxhilt = "1.0.0"
androidxlifecycle = "2.6.1"
navigation = "2.6.0-beta01"
androidxtest = "1.5.2"
coil = "2.3.0"
compose-bom = "2023.04.00-alpha04"
constraintlayout = "1.1.0-alpha09"
composecompiler = "1.4.5"
composesnapshot = "-" # a single character = no snapshot
coroutines = "1.6.4"
dagger = "2.45"
hilt = "2.45"
icons = "1.0.0"
kotlin = "1.8.20"
kotlin-immutable = "0.3.5"
ktlint = "0.40.0"
material3 = "1.1.0"
okhttp = "4.11.0"
paging = "3.1.1"
retrofit = "2.9.0"
room = "2.5.1"
threetenbp = "1.5.2"
serialization = "1.5.0"
exoplayer = "2.18.6"
media3 = "1.0.1"
pdftron = "9.3.1"
pdfviewer = "3.2.0-beta.1"
compileSdk = "33"
minSdk = "24"
targetSdk = "33"
core-ktx = "1.10.1"
junit = "4.13.2"
androidx-test-ext-junit = "1.1.5"
espresso-core = "3.5.1"
appcompat = "1.6.1"
uiautomator = "2.2.0"
benchmark-macro-junit4 = "1.2.0-alpha14"
androidx-baselineprofile = "1.2.0-alpha13"
profileinstaller = "1.3.1"
androidx-appcompat-appcompat = "1.6.1"
material = "1.9.0"
review = "2.0.1"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
android-lint = { id = "com.android.lint", version.ref = "agp" }
cacheFixPlugin = { id = "org.gradle.android.cache-fix", version = "2.7.1" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
ksp = "com.google.devtools.ksp:1.8.20-1.0.10"
gms-googleServices = "com.google.gms.google-services:4.3.15"
firebase-crashlytics = "com.google.firebase.crashlytics:2.9.5"
spotless = "com.diffplug.spotless:6.18.0"
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "serialization" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
androidTest = { id = "com.android.test", version.ref = "agp" }
androidx-baselineprofile = { id = "androidx.baselineprofile", version.ref = "androidx-baselineprofile" }

[libraries]
accompanist-flowlayout = { module = "com.google.accompanist:accompanist-flowlayout", version.ref = "accompanist" }
accompanist-insetsui = { module = "com.google.accompanist:accompanist-insets-ui", version.ref = "accompanist" }
accompanist-swiperefresh = { module = "com.google.accompanist:accompanist-swiperefresh", version.ref = "accompanist" }
accompanist-placeholder = { module = "com.google.accompanist:accompanist-placeholder-material", version.ref = "accompanist" }
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
accompanist-navigation-animation = { module = "com.google.accompanist:accompanist-navigation-animation", version.ref = "accompanist" }
accompanist-navigation-material = { module = "com.google.accompanist:accompanist-navigation-material", version.ref = "accompanist" }
accompanist-web = { module = "com.google.accompanist:accompanist-webview", version.ref = "accompanist" }

exoplayer-core = { module = "com.google.android.exoplayer:exoplayer-core", version.ref = "exoplayer" }
exoplayer-okhttp = { module = "com.google.android.exoplayer:extension-okhttp", version.ref = "exoplayer" }

rebugger = "com.github.theapache64:rebugger:1.0.0-alpha05"
proguard-snippets = "com.infstory:proguard-snippets:1.0.0"
media = "androidx.media:media:1.6.0"
palette = "androidx.palette:palette-ktx:1.0.0"
radiography = "com.squareup.radiography:radiography:2.4.1"
profile-installer = "androidx.profileinstaller:profileinstaller:1.3.1"
pdfkit = "com.pspdfkit:pspdfkit:8.2.1"
rive = "app.rive:rive-android:4.0.0"
startup = "androidx.startup:startup-runtime:1.1.1"
tools-desugarjdklibs = "com.android.tools:desugar_jdk_libs:2.0.3"

androidx-activity-compose = "androidx.activity:activity-compose:1.7.1"
androidx-activity = "androidx.activity:activity:1.7.1"
androidx-appcompat-resources = "androidx.appcompat:appcompat-resources:1.6.1"
androidx-archCoreTesting = "androidx.arch.core:core-testing:2.2.0"
androidx-browser = "androidx.browser:browser:1.5.0"
androidx-collection = "androidx.collection:collection-ktx:1.2.0"
androidx-core = "androidx.core:core-ktx:1.10.0"
androidx-dynamicanimation = "androidx.dynamicanimation:dynamicanimation-ktx:1.0.0-alpha03"
androidx-emoji = "androidx.emoji:emoji:1.1.0"

androidx-hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "androidxhilt" }
androidx-hilt-compose = "androidx.hilt:hilt-navigation-compose:1.0.0"
androidx-hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "androidxhilt" }
androidx-hilt-navigation = { module = "androidx.hilt:hilt-navigation", version.ref = "androidxhilt" }

media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3" }

hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
hilt-gradlePlug = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt" }

#androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidxlifecycle" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidxlifecycle" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidxlifecycle" }
androidx-lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "androidxlifecycle" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidxlifecycle" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "androidxlifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidxlifecycle" }

androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }

lottie-core = "com.airbnb.android:lottie:6.0.0"
lottie-compose = "com.airbnb.android:lottie-compose:6.0.0"

androidx-paging-common = { module = "androidx.paging:paging-common-ktx", version.ref = "paging" }
androidx-paging-runtime = { module = "androidx.paging:paging-runtime-ktx", version.ref = "paging" }
androidx-paging-compose = "androidx.paging:paging-compose:1.0.0-alpha19"

androidx-palette = "androidx.palette:palette:1.0.0"

androidx-room-common = { module = "androidx.room:room-common", version.ref = "room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-paging = { module = "androidx.room:room-paging", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-testing = { module = "androidx.room:room-testing", version.ref = "room" }

androidx-test-core = { module = "androidx.test:core", version.ref = "androidxtest" }
androidx-test-junit = "androidx.test.ext:junit-ktx:1.1.5"
androidx-test-rules = { module = "androidx.test:rules", version.ref = "androidxtest" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidxtest" }

androidx-work-runtime = "androidx.work:work-runtime-ktx:2.8.1"

appauth = "net.openid:appauth:0.8.1"

coil-coil = { module = "io.coil-kt:coil", version.ref = "coil" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
coil-gif = { module = "io.coil-kt:coil-gif", version.ref = "coil" }

compose-bom = { module = "dev.chrisbanes.compose:compose-bom", version.ref = "compose-bom" }
compose-runtime-runtime = { module = "androidx.compose.runtime:runtime" }
compose-animation-animation = { module = "androidx.compose.animation:animation" }
compose-foundation-foundation = { module = "androidx.compose.foundation:foundation" }
compose-foundation-layout = { module = "androidx.compose.foundation:foundation-layout" }
compose-material-iconsext = { module = "androidx.compose.material:material-icons-extended" }
compose-material-material = { module = "androidx.compose.material:material" }
compose-material-material3 = { module = "androidx.compose.material3:material3" }
compose-ui-test = { module = "androidx.compose.ui:ui-test-junit4" }
compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-ui-ui = { module = "androidx.compose.ui:ui" }
compose-ui-textfonts = { module = "androidx.compose.ui:ui-text-google-fonts" }
compose-ui-util = { module = "androidx.compose.ui:ui-util" }
compose-ui-viewbinding = { module = "androidx.compose.ui:ui-viewbinding" }
compose-constraintlayout = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "constraintlayout"}

fetch = "com.github.alashow:Fetch:3.1.62"
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }
dagger-dagger = { module = "com.google.dagger:dagger", version.ref = "dagger" }

google-bom = "com.google.firebase:firebase-bom:32.0.0"
google-crashlyticsGradle = "com.google.firebase:firebase-crashlytics-gradle:2.9.5"
google-gmsGoogleServices = "com.google.gms:google-services:4.3.15"
google-perfPlug = "com.google.firebase:perf-plugin:1.4.2"
google-analytics = { module = "com.google.firebase:firebase-analytics-ktx" }
google-crashlytics = { module = "com.google.firebase:firebase-crashlytics-ktx" }
google-dynamic_links = { module = "com.google.firebase:firebase-dynamic-links-ktx" }
google-auth = { module = "com.google.firebase:firebase-auth-ktx" }
google-auth-coroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services:1.6.4"
google-firestore = { module = "com.google.firebase:firebase-firestore-ktx" }
google-messaging = { module = "com.google.firebase:firebase-messaging-ktx" }
google-remoteConfig = { module = "com.google.firebase:firebase-config-ktx" }
google-storage = { module = "com.google.firebase:firebase-storage-ktx" }

google-review = { module = "com.google.android.play:review-ktx", version.ref = "review" }

firestore-ktx = "dev.gitlive:firebase-firestore:1.8.0"

junit = "junit:junit:4.13.2"

pdftron = { module = "com.pdftron:pdftron", version.ref = "pdftron" }
pdftron-tools = { module = "com.pdftron:tools", version.ref = "pdftron" }
pdftron-standard = { module = "com.pdftron:pdftron-standard", version.ref = "pdftron" }

kotlin-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlin-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlin-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
kotlin-extensions = { module = "org.jetbrains.kotlin:kotlin-android-extensions", version.ref = "kotlin" }
kotlin-gradlePlug = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
kotlin-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlin-immutable" }

icons-feather = { module = "br.com.devsrsouza.compose.icons.android:feather", version.ref = "icons" }
icons-font-awesome = { module = "br.com.devsrsouza.compose.icons.android:font-awesome", version.ref = "icons" }
icons-tabler = { module = "br.com.devsrsouza.compose.icons.android:tabler-icons", version.ref = "icons" }

leakCanary = "com.squareup.leakcanary:leakcanary-android:2.10"
leakCanary-process = "com.squareup.leakcanary:leakcanary-android-process:2.9.1"

okhttp-loggingInterceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
okhttp-okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }

retrofit-gsonConverter = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
retrofit-serialization = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter:0.8.0"
retrofit-retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
pdfviewer = { module = "com.github.barteksc:android-pdf-viewer", version.ref = "pdfviewer" }

threeTenAbp = "com.jakewharton.threetenabp:threetenabp:1.4.4"
timber = "com.jakewharton.timber:timber:5.0.1"
tracing = "androidx.tracing:tracing-ktx:1.1.0"
dataStore = "androidx.datastore:datastore-preferences:1.0.0"
truth = "com.google.truth:truth:1.1.3"
jsoup = "org.jsoup:jsoup:1.15.1"
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
junit-junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
uiautomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "uiautomator" }
benchmark-macro-junit4 = { group = "androidx.benchmark", name = "benchmark-macro-junit4", version.ref = "benchmark-macro-junit4" }
profileinstaller = { group = "androidx.profileinstaller", name = "profileinstaller", version.ref = "profileinstaller" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat-appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
